### ISSUE TITLE
rails 3

### ISSUE THREAD

**Issue by pfcfernandez** [operand/cheetah#2]
Hey will this work on rails 3?
I need to sent to cheetahmail all emails we grab when someone register to our site..

Thanks!

**Comment by operand** [comment]
It's been a while since I've maintained or used it but as long as it still
works against the api I don't see any reason why it wouldn't work with
Rails 3. It's independent of Rails.

Good luck!

**Comment by scottillogical** [comment]
There is an issue with the way some of the files are required, I think

NameError (uninitialized constant Cheetah::Cheetah):
